language: ruby
os: linux
dist: bionic

services:
  - postgresql
  - redis

cache:
  bundler: true

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - gem update --system 3.1.4
  - gem install bundler:2.1.4

before_script:
- cp config/database.yml.travis config/database.yml
- RAILS_ENV=test bundle exec rails db:prepare

rvm:
  - 2.5.8
  - 2.6.6

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  jobs:
    - "RAILS_VERSION=6.0.3.4"
