language: ruby
os: linux
dist: focal

cache:
  bundler: true
  apt: true

addons:
  postgresql: "15"
  apt:
    update: true
    packages:
      - postgresql-15
      - postgresql-client-15

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/15/main/postgresql.conf
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/15/main/pg_hba.conf
  - sudo pg_ctlcluster 15 main restart
  - gem update --system --no-document
  - gem install bundler:2.5.18 --no-document

before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rails db:prepare

script:
  - RAILS_ENV=test bundle exec rake ci

rvm:
  - 3.2.5

env:
  global:
    - PGVER=15
    - PGPORT=5432
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CURATOR_SOLR_URL=http://127.0.0.1:8983/solr/curator_development
    - AZURE_DERIVATIVES_URL=http://127.0.0.1:8888/devstoreaccount1/derivatives
    - IIIF_SERVER_URL=https://iiifdev.bpl.org/iiif/2/
    - ARK_MANAGER_DEFAULT_BASE_URL=https://search-dc3dev.bpl.org
    - ARK_MANAGER_DEFAULT_NAMESPACE=bpl-dev
    - ARK_MANAGER_OAI_NAMESPACE=oai-dev
  jobs:
    - "RAILS_VERSION=7.1.5.1"
