language: ruby
os: linux
dist: bionic

cache:
  bundler: true
  apt: true

addons:
  postgresql: "12"
  apt:
    update: true
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - gem update --system --no-document
  - gem install bundler:2.2.24 --no-document

before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rails db:prepare

rvm:
  - 2.7.4

env:
  global:
    - PGVER=12
    - PGPORT=5432
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CURATOR_SOLR_URL=http://127.0.0.1:8983/solr/curator_development
    - AZURE_DERIVATIVES_URL=http://127.0.0.1:8888/devstoreaccount1/derivatives
    - IIIF_SERVER_URL=https://iiifdev.bpl.org/iiif/2/
    - ARK_MANAGER_DEFAULT_BASE_URL=https://search-dc3dev.bpl.org
    - ARK_MANAGER_DEFAULT_NAMESPACE=bpl-dev
    - ARK_MANAGER_OAI_NAMESPACE=oai-dev
  jobs:
    - "RAILS_VERSION=6.0.4"
