version: '0.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ARK_MANAGER_DATABASE_USER: postgres
      - ARK_MANAGER_DATABASE_PASSWROD=sekret
      - ARK_MANAGER_DATABASE_HOST=db
      - ARK_MANAGER_DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/
      - SETTINGS__ENABLE_STOMP=false
      - SETTINGS__REDIS__HOSTNAME=redis
    volumes:
       - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=sekret
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis

volumes:
  postgres-data:
