version: '3'

services:
  app:
    container_name: ark_manager_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - .:/ark-manager-app
    ports:
      - "3002:3000"
    env_file: .env
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - WEB_CONCURRENCY=0
      - ARK_MANAGER_DATABASE_HOST=pg_db
      - ARK_MANAGER_DATABASE_PORT=5432
      - ARK_MANAGER_REDIS_CACHE_URL=redis://cache:6379/0
    depends_on:
      - pg_db
      - cache
  pg_db:
    restart: unless-stopped
    mem_reservation: 32m
    container_name: ark_manager_db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  cache:
    container_name: ark_manager_cache
    image: redis:latest
    command: >
      bash -c "echo 1 > /proc/sys/vm/overcommit_memory &&
      redis-server --databases 1 --maxmemory 16mb --maxmemory-policy allkeys-lfu"
    ulimits:
      nproc: 16384
    sysctls:
      net.core.somaxconn: 1024

volumes:
  postgres-data:
