version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - .:/ark-manager
    ports:
      - "3002:3000"
    volumes:
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=pg_db
      - REDIS_DOCKER_URL=cache
    depends_on:
      - pg_db
      - cache
  pg_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  cache:
    image: redis:latest

volumes:
  postgres-data:
  gem_cache:
